### ISSUE TITLE
Docs CLI page isn't displaying details?

### ISSUE THREAD

**Issue by PinkShnack** [GuckLab/MPL-Data-Cast#19]
Just noticed that the pages:

https://mpl-data-cast.readthedocs.io/en/latest/sec_cli.html#sec-cli
https://mpl-data-cast.readthedocs.io/en/stable/sec_cli.html

don't display the click information as it probably should (as I see from the `.rst` file).

Is this expected?

**Comment by paulmueller** [comment]
Not expected, something's wrong with the docs, maybe the click-sphinx extension not loaded...

**Comment by paulmueller** [comment]
Issue was recent refactoring of the CLI module.

https://mpl-data-cast.readthedocs.io/en/latest/sec_cli.html
