### ISSUE TITLE
Enh: Have different settings of shown folder levels for input and output directory.

### ISSUE THREAD

**Issue by B-Hartmann** [GuckLab/MPL-Data-Cast#23]
Users are more interested in the input directory than in the output directory. Also, having potentially thousands of files to show in the output directory, for example, when mpldc is used to copy data to a general network drive location, makes the software slower.

**Comment by paulmueller** [comment]
In 0.6.0, we have a `QtGui.QFileSystemModel()` which should not have these drawbacks.
